### PR TITLE
Improved UX by allowing clicks on path to move handle.

### PR DESCRIPTION
**Pull request by jon-joshua**
Variable `--round-slider-click-area` sets size of shadow-path that can be clicked and dragged.

### CODE REVIEW

**Comment by ebrensi** [comment]
Is there a problem with this enhancement?  Why has it not been merged?

**Comment by zsarnett** [comment]
The big issue is that the PR is touching a lot of code. Update the PR to only be updating the code addition and then this may have more potential to be merged

**Comment by thomasloven** [comment]
Hi.

I'm sorry I haven't had the time to take a good look at this for so long.
@zsarnett is right though - the large number of changes makes it hard to overview.

... and I liked my formating... ;)

**Comment by thomasloven** [comment]
I'd also like a way to disable this functionality

**Comment by thomasloven** [comment]
I just published version 0.5.0 which includes bar-touching.
Thank you very much for doing the grunt work! I could use your solution almost entirely, but with a few tweaks for improved touch screen UX.

**Pull request closed without merging**
